services:
  postgres:
    image: postgres:17
    container_name: mini-idm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mini_idm
      POSTGRES_USER: idm_user
      POSTGRES_PASSWORD: idm_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:8
    container_name: mini-idm-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: mini_idm
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: